# Generated by Django 3.1.5 on 2021-01-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(default='No bio entered', max_length=200),
        ),
    ]
