# Generated by Django 3.1.5 on 2021-01-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210107_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture_link',
            field=models.TextField(default='https://upload.wikimedia.org/wikipedia/en/1/1b/NPC_wojak_meme.png', max_length=250),
        ),
    ]
