# Generated by Django 3.1.5 on 2021-01-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210105_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default='2021-01-07 06:00:00.000000-08:00'),
        ),
    ]
