# Generated by Django 3.1.5 on 2021-01-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default='2021-01-06 06:00:00.000000-08:00'),
        ),
    ]
