# Generated by Django 3.1.5 on 2021-01-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
