# Generated by Django 3.1.5 on 2021-01-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_nestedcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NestedComment',
        ),
    ]
